batch_size: 64
bbox_dim: 4
decoder_layer_nb: 8
dropout: 0.2
encoder_layer_nb: 8
hidden_dim: 128
image_size: !!python/tuple
- 640
- 480
input_frames: 30
lr: 0.0001
output_frames: 60
scheduler_factor: 0.5
scheduler_patience: 15
