batch_size: 64
dropout: 0.2
hidden_depth: 8
hidden_dim: 128
image_size: !!python/tuple
- 640
- 480
input_frames: 30
lr: 0.0005
output_frames: 60
position_dim: 6
scheduler_factor: 0.9
scheduler_patience: 10
size_dim: 4
